name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu_latest
    steps:
      - name: Print Greeting
        run: echo "Hello world !!"
      - name: Print Goodbye
        run: echo "Ok done Bye !!"
